### ISSUE TITLE
Egg broken (1.3)

### ISSUE THREAD

**Issue by stonor** [anybox/buttervolume#10]
The buttervolume egg v. 1.3 (https://pypi.python.org/pypi/buttervolume/1.3) seems to broken.

```
# pip3 install buttervolume 
Collecting buttervolume
  Downloading buttervolume-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c_alp5nk/buttervolume/setup.py", line 17, in <module>
        + open('CHANGES.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c_alp5nk/buttervolume/
```

Guess the CHANGES.rst file is missing in the package.

**Comment by ccomb** [comment]
Thanks for reporting! I've pushed and released a version fixed with a MANIFEST including the missing file
